global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: prometheus

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
      #    authorization:
      #      credentials_file: /etc/prometheus/prometheus-token
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/vault-lb-ca.pem
      # insecure_skip_verify: true
    static_configs:
      - targets: ['vault-dev.vault202.local:8200']

  - job_name: node-exporter
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:PrometheusScrape
            values:
              - Enabled
